# Configuration file for prettier.
# Read more at: https://prettier.io/docs/en/options.html

printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: 'all'
bracketSpacing: false
arrowParens: 'avoid'
requirePragma: false
insertPragma: false
