
// tslint:disable
// GENERATED BY THE UNION OF WAVESURF ROBOTS

import {
  Resource,
  ResourceDetail,
  ResourceList,
} from '@api/backendapi.base';


export interface Device extends Resource {}

export interface DeviceList extends ResourceList {
  devices: Device[];
}

export interface DeviceDetail extends ResourceDetail {
	vendor: string;
	model: string;
	serialNo: string;
	role: string;
	osVersion: string;
	hostname: string;
}

export interface Intf extends Resource {}

export interface IntfList extends ResourceList {
  intves: Intf[];
}

export interface IntfDetail extends ResourceDetail {
}

// end of file