
// GENERATED BY THE UNION OF WAVESURF ROBOTS

/*
Copyright (c) 2019 WaveSurf Systems Inc. All rights reserved.
*/

import {NgModule} from '@angular/core';

import {ComponentsModule} from '../../common/components/module';
import {SharedModule} from '../../shared.module';

import {ActionbarComponent} from './detail/actionbar/component';
import { IntfDetailComponent} from './detail/component';
import { IntfListComponent} from './list/component';
import { IntfRoutingModule} from './routing';

@NgModule({
  imports: [SharedModule, ComponentsModule, IntfRoutingModule],
  declarations: [IntfListComponent,  IntfDetailComponent, ActionbarComponent],
})
export class  IntfModule {}
