
// GENERATED BY THE UNION OF WAVESURF ROBOTS

/*
Copyright (c) 2019 WaveSurf Systems Inc. All rights reserved.
*/

import {NgModule} from '@angular/core';
import {Route, RouterModule} from '@angular/router';
import {DEFAULT_ACTIONBAR} from '../../common/components/actionbars/routing';

import { IntfDetailComponent} from './detail/component';
import { IntfListComponent} from './list/component';

const INTF_LIST_ROUTE: Route = {
  path: '',
  component:  IntfListComponent,
  data: {
    breadcrumb: 'Interfaces',
    link: ['', 'intf'],
  },
};

const INTF_DETAIL_ROUTE: Route = {
  path: ':resourceName',
  component: IntfDetailComponent,
  data: {
    breadcrumb: '{{ resourceName }}',
    parent: INTF_LIST_ROUTE,
  },
};

@NgModule({
  imports: [RouterModule.forChild([INTF_LIST_ROUTE, INTF_DETAIL_ROUTE, DEFAULT_ACTIONBAR])],
  exports: [RouterModule],
})
export class  IntfRoutingModule {}
