
// GENERATED BY THE UNION OF WAVESURF ROBOTS

/*
Copyright (c) 2019 WaveSurf Systems Inc. All rights reserved.
*/

import {NgModule} from '@angular/core';

import {ComponentsModule} from '../../common/components/module';
import {SharedModule} from '../../shared.module';

import {ActionbarComponent} from './detail/actionbar/component';
import { DeviceDetailComponent} from './detail/component';
import { DeviceListComponent} from './list/component';
import { DeviceRoutingModule} from './routing';

@NgModule({
  imports: [SharedModule, ComponentsModule, DeviceRoutingModule],
  declarations: [DeviceListComponent,  DeviceDetailComponent, ActionbarComponent],
})
export class  DeviceModule {}
