
// GENERATED BY THE UNION OF WAVESURF ROBOTS

/*
Copyright (c) 2019 WaveSurf Systems Inc. All rights reserved.
*/

import {NgModule} from '@angular/core';
import {Route, RouterModule} from '@angular/router';
import {DEFAULT_ACTIONBAR} from '../../common/components/actionbars/routing';

import { DeviceDetailComponent} from './detail/component';
import { DeviceListComponent} from './list/component';

const DEVICE_LIST_ROUTE: Route = {
  path: '',
  component:  DeviceListComponent,
  data: {
    breadcrumb: 'Devices',
    link: ['', 'device'],
  },
};

const DEVICE_DETAIL_ROUTE: Route = {
  path: ':resourceName',
  component: DeviceDetailComponent,
  data: {
    breadcrumb: '{{ resourceName }}',
    parent: DEVICE_LIST_ROUTE,
  },
};

@NgModule({
  imports: [RouterModule.forChild([DEVICE_LIST_ROUTE, DEVICE_DETAIL_ROUTE, DEFAULT_ACTIONBAR])],
  exports: [RouterModule],
})
export class  DeviceRoutingModule {}
