// GENERATED BY THE UNION OF WAVESURF ROBOTS

/*
Copyright (c) 2019 WaveSurf Systems Inc. All rights reserved.
*/

import {NgModule} from '@angular/core';
import {RouterModule, Routes} from '@angular/router';
import {AuthGuard} from '../common/services/guard/auth';
import {ChromeComponent} from './component';

const routes: Routes = [
  {path: '', redirectTo: '/dashboard', pathMatch: 'full'},
  {
    path: '',
    component: ChromeComponent,
    canActivate: [AuthGuard],
    children: [
      {
        path: 'error',
        loadChildren: 'error/module#ErrorModule',
      },

      // Dashboard
      {
        path: 'dashboard',
        loadChildren: 'dashboard/module#DashboardModule',
      },

      // Topology
      {
        path: 'topology',
        loadChildren: 'topology/module#TopologyModule',
      },

      // Infra group
      {
        path: 'infra',
        loadChildren: 'resource/infra/module#InfraModule',
      },
      {
        path: 'cluster',
        loadChildren: 'resource/infra/cluster/module#ClusterModule',
      },
      {
        path: 'namespace',
        loadChildren: 'resource/infra/namespace/module#NamespaceModule',
      },

      // Others
      {
        path: 'settings',
        loadChildren: 'settings/module#SettingsModule',
      },
      {
        path: 'about',
        loadChildren: 'about/module#AboutModule',
      },

      {
        path: 'create',
        loadChildren: 'create/module#CreateModule',
      },
      {
        path: 'log',
        loadChildren: 'logs/module#LogsModule',
      },
      {
        path: 'shell',
        loadChildren: 'shell/module#ShellModule',
      },
      {
        path: 'search',
        loadChildren: 'search/module#SearchModule',
        runGuardsAndResolvers: 'always',
      },
      // generated
      {
        path: 'intf',
        loadChildren: 'resource/intf/module#IntfModule',
      },
      {
        path: 'device',
        loadChildren: 'resource/device/module#DeviceModule',
      },
    ],
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class ChromeRoutingModule {}
