
// GENERATED BY THE UNION OF WAVESURF ROBOTS

/*
Copyright (c) 2019 WaveSurf Systems Inc. All rights reserved.
*/

import {Component} from '@angular/core';

@Component({
  selector: 'kd-intf-list-view',
  template: '<kd-intf-list></kd-intf-list>',
})
export class IntfListComponent {}
