
// GENERATED BY THE UNION OF WAVESURF ROBOTS

import {HttpParams} from '@angular/common/http';
import {ChangeDetectionStrategy, ChangeDetectorRef, Component, Input} from '@angular/core';
import {Metric} from '@api/backendapi';
import { Intf, IntfList} from '@api/gen.v1';
import {Observable} from 'rxjs/Observable';

import {ResourceListBase} from '../../../resources/list';
import {NotificationsService} from '../../../services/global/notifications';
import {EndpointManager} from '../../../services/resource/endpoint';
import {Resource} from '../../../services/resource/endpoint.gen';
import {ResourceService} from '../../../services/resource/resource';
import {MenuComponent} from '../../list/column/menu/component';
import {ListGroupIdentifier} from '../groupids';
import {ListIdentifier} from '../listids.gen';

@Component({
  selector: 'kd-intf-list',
  templateUrl: './template.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IntfListComponent extends ResourceListBase<IntfList, Intf> {
  @Input() endpoint = EndpointManager.resource(Resource.intf).list();
  @Input() showMetrics = false;
  cumulativeMetrics: Metric[];

  constructor(
    private readonly intf_: ResourceService<IntfList>,
    notifications: NotificationsService,
    cdr: ChangeDetectorRef,
  ) {
    super('intf',
      notifications,
      cdr,
    );
    this.id = ListIdentifier.intf;
    this.groupId = ListGroupIdentifier.setups;

    // Register action columns.
    this.registerActionColumn<MenuComponent>('menu', MenuComponent);

  }

  getResourceObservable(params?: HttpParams): Observable<IntfList> {
    return this.intf_.get(this.endpoint, undefined, params);
  }

  map(intfList: IntfList): Intf[] {
    return intfList.items;
  }
  getDisplayColumns(): string[] {
    return ['name',  'age'];
  }
}
