
// GENERATED BY THE UNION OF WAVESURF ROBOTS
export enum ListIdentifier {
  // preexisting
  cluster = 'clusterList',
  clusterRole = 'clusterRoleList',
  namespace = 'namespaceList',
  node = 'nodeList',
  persistentVolume = 'persistentVolumeList',
  storageClass = 'storageClassList',
  cronJob = 'cronJobList',
  crd = 'crdList',
  crdObject = 'crdObjectList',
  job = 'jobList',
  deployment = 'deploymentList',
  daemonSet = 'daemonSetList',
  pod = 'podList',
  replicaSet = 'replicaSetList',
  ingress = 'ingressList',
  service = 'serviceList',
  configMap = 'configMapList',
  persistentVolumeClaim = 'persistentVolumeClaimList',
  secret = 'secretList',
  replicationController = 'replicationControllerList',
  statefulSet = 'statefulSetList',
  event = 'event',
  resource = 'resource',
  plugin = 'plugin',
  // generated
  intf = 'intfList',
  device = 'deviceList',
}
