
export const data = {
  "objects": {
    "kind": "DiscoveredDeviceList",
      "apiVersion": "v1",
    "metadata": {
      "selfLink": "/api/v1/discovereddevices",
      "resourceVersion": "12813",
    },
    "items": [
      {
        "status": {
          "faults": "null",
          "vendor": "juniper",
          "hostName": "jnpr-dist-1",
          "serialNo": "",
          "ipv4Net": "172.17.0.4",
          "id": "1",
          "role": "distribution",
          "macAddress": "",
          "ports": [
            "ge-0/0/514",
            "ge-0/0/522",
            "ge-0/0/527",
            "ge-0/0/533",
            "ge-0/0/540",
            "ge-0/0/549",
            "ge-0/0/512",
            "ge-0/0/526",
            "ge-0/0/528",
            "ge-0/0/543",
            "ge-0/0/513",
            "ge-0/0/530",
            "ge-0/0/542",
            "ge-0/0/516",
            "ge-0/0/520",
            "ge-0/0/525",
            "ge-0/0/538",
            "ge-0/0/539",
            "ge-0/0/548",
            "ge-0/0/518",
            "ge-0/0/521",
            "ge-0/0/524",
            "ge-0/0/531",
            "ge-0/0/532",
            "ge-0/0/544",
            "ge-0/0/545",
            "ge-0/0/515",
            "ge-0/0/523",
            "ge-0/0/529",
            "ge-0/0/534",
            "ge-0/0/535",
            "ge-0/0/537",
            "ge-0/0/517",
            "ge-0/0/541",
            "ge-0/0/546",
            "ge-0/0/519",
            "ge-0/0/536",
            "ge-0/0/547",
          ],
          "model": "EX4300",
        },
        "metadata": {
          "name": "dev-1",
          "selfLink": "/api/v1/discovereddevices/dev-1",
          "resourceVersion": "184",
          "creationTimestamp": "null",
        },
        "spec": "null",
      },
      {
        "status": {
          "faults": "null",
          "vendor": "cisco",
          "hostName": "cisco-dist-1",
          "serialNo": "",
          "ipv4Net": "172.17.0.5",
          "id": "2",
          "role": "distribution",
          "macAddress": "",
          "ports": [
            "Gi1/0/22",
            "Gi1/0/29",
            "Gi1/0/2",
            "Gi1/0/23",
            "Gi1/0/24",
            "Gi1/0/25",
            "Gi1/0/8",
            "Gi1/0/13",
            "Gi1/0/15",
            "Gi1/0/16",
            "Gi1/0/28",
            "Gi1/0/3",
            "Gi1/0/4",
            "Gi1/0/5",
            "Gi1/0/14",
            "Gi1/0/21",
            "Gi1/0/9",
            "Gi1/0/17",
            "Gi1/0/27",
            "Gi1/0/1",
            "Gi1/0/7",
            "Gi1/0/10",
            "Gi1/0/19",
            "Gi1/0/20",
            "Gi1/0/26",
            "Gi1/0/18",
            "Gi1/0/6",
            "Gi1/0/11",
            "Gi1/0/12",
          ],
          "model": "Cat36XX",
        },
        "metadata": {
          "name": "dev-2",
          "selfLink": "/api/v1/discovereddevices/dev-2",
          "resourceVersion": "185",
          "creationTimestamp": null,
        },
        "spec": null,
      },
      {
        "status": {
          "faults": null,
          "vendor": "cisco",
          "hostName": "cisco-access-1",
          "serialNo": "",
          "ipv4Net": "172.17.0.6",
          "id": "3",
          "role": "access",
          "macAddress": "",
          "ports": [
            "Gi1/0/7",
            "Gi1/0/12",
            "Gi1/0/14",
            "Gi1/0/19",
            "Gi1/0/4",
            "Gi1/0/11",
            "Gi1/0/17",
            "Gi1/0/22",
            "Gi1/0/28",
            "Gi1/0/10",
            "Gi1/0/18",
            "Gi1/0/27",
            "Gi1/0/29",
            "Gi1/0/16",
            "Gi1/0/9",
            "Gi1/0/5",
            "Gi1/0/6",
            "Gi1/0/8",
            "Gi1/0/21",
            "Gi1/0/25",
            "Gi1/0/1",
            "Gi1/0/20",
            "Gi1/0/15",
            "Gi1/0/23",
            "Gi1/0/24",
            "Gi1/0/26",
            "Gi1/0/3",
            "Gi1/0/13",
            "Gi1/0/2",
          ],
          "model": "Cat36XX",
        },
        "metadata": {
          "name": "dev-3",
          "selfLink": "/api/v1/discovereddevices/dev-3",
          "resourceVersion": "188",
          "creationTimestamp": null,
        },
        "spec": null,
      },
      {
        "status": {
          "faults": null,
          "vendor": "cisco",
          "hostName": "cisco-access-2",
          "serialNo": "",
          "ipv4Net": "172.17.0.7",
          "id": "4",
          "role": "access",
          "macAddress": "",
          "ports": [
            "Gi1/0/23",
            "Gi1/0/15",
            "Gi1/0/16",
            "Gi1/0/21",
            "Gi1/0/24",
            "Gi1/0/28",
            "Gi1/0/4",
            "Gi1/0/14",
            "Gi1/0/25",
            "Gi1/0/26",
            "Gi1/0/13",
            "Gi1/0/22",
            "Gi1/0/6",
            "Gi1/0/10",
            "Gi1/0/11",
            "Gi1/0/19",
            "Gi1/0/27",
            "Gi1/0/29",
            "Gi1/0/2",
            "Gi1/0/9",
            "Gi1/0/12",
            "Gi1/0/17",
            "Gi1/0/20",
            "Gi1/0/1",
            "Gi1/0/3",
            "Gi1/0/5",
            "Gi1/0/18",
            "Gi1/0/7",
            "Gi1/0/8",
          ],
          "model": "Cat36XX",
        },
        "metadata": {
          "name": "dev-4",
          "selfLink": "/api/v1/discovereddevices/dev-4",
          "resourceVersion": "191",
          "creationTimestamp": null,
        },
        "spec": null,
      },
      {
        "status": {
          "faults": null,
          "vendor": "wavesurf",
          "hostName": "sonic1",
          "serialNo": "",
          "ipv4Net": "172.17.0.2",
          "id": "5",
          "role": "wavesurf",
          "macAddress": "",
          "ports": [],
          "model": "ws-vm-1.0",
        },
        "metadata": {
          "name": "dev-5",
          "selfLink": "/api/v1/discovereddevices/dev-5",
          "resourceVersion": "193",
          "creationTimestamp": null,
        },
        "spec": null,
      },
      {
        "status": {
          "faults": null,
          "vendor": "wavesurf",
          "hostName": "sonic2",
          "serialNo": "",
          "ipv4Net": "172.17.0.3",
          "id": "6",
          "role": "wavesurf",
          "macAddress": "",
          "ports": [],
          "model": "ws-vm-1.0",
        },
        "metadata": {
          "name": "dev-6",
          "selfLink": "/api/v1/discovereddevices/dev-6",
          "resourceVersion": "198",
          "creationTimestamp": null,
        },
        "spec": null,
      },
      {
        "status": {
          "faults": null,
          "vendor": "aruba",
          "hostName": "ap1",
          "serialNo": "",
          "ipv4Net": "172.17.0.8",
          "id": "7",
          "role": "wireless-access-point",
          "macAddress": "",
          "ports": [],
          "model": "205",
        },
        "metadata": {
          "name": "dev-7",
          "selfLink": "/api/v1/discovereddevices/dev-7",
          "resourceVersion": "238",
          "creationTimestamp": null,
        },
        "spec": null,
      },
      {
        "status": {
          "faults": null,
          "vendor": "aruba",
          "hostName": "010203040502",
          "serialNo": "",
          "ipv4Net": "172.17.0.9",
          "id": "8",
          "role": "wireless-access-point",
          "macAddress": "",
          "ports": [],
          "model": "205",
        },
        "metadata": {
          "name": "dev-8",
          "selfLink": "/api/v1/discovereddevices/dev-8",
          "resourceVersion": "239",
          "creationTimestamp": null,
        },
        "spec": null,
      },
    ],
  },
  "links": {
    "kind": "DiscoveredLinkList",
    "apiVersion": "v1",
    "metadata": {
      "selfLink": "/api/v1/discoveredlinks",
      "resourceVersion": "13013",
    },
    "items": [
      {
        "spec": "null",
        "status": {
          "localDevice": "cisco-access-1",
          "localPort": "GigabitEthernet1/0/27",
          "remoteDevice": "ap1",
          "remotePort": "bond0",
          "faults": "null",
        },
        "metadata": {
          "name": "cisco-access-1@GigabitEthernet1/0/27",
          "selfLink": "/api/v1/discoveredlinks/cisco-access-1%40GigabitEthernet1%2F0%2F27",
          "resourceVersion": "242",
          "creationTimestamp": "null",
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "cisco-access-1",
          "localPort": "GigabitEthernet1/0/28",
          "remoteDevice": "cisco-dist-1",
          "remotePort": "GigabitEthernet1/0/27",
          "faults": null,
        },
        "metadata": {
          "name": "cisco-access-1@GigabitEthernet1/0/28",
          "selfLink": "/api/v1/discoveredlinks/cisco-access-1%40GigabitEthernet1%2F0%2F28",
          "resourceVersion": "218",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "cisco-access-1",
          "localPort": "GigabitEthernet1/0/29",
          "remoteDevice": "jnpr-dist-1",
          "remotePort": "ge-0/0/547",
          "faults": null,
        },
        "metadata": {
          "name": "cisco-access-1@GigabitEthernet1/0/29",
          "selfLink": "/api/v1/discoveredlinks/cisco-access-1%40GigabitEthernet1%2F0%2F29",
          "resourceVersion": "202",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "cisco-access-2",
          "localPort": "GigabitEthernet1/0/27",
          "remoteDevice": "010203040502",
          "remotePort": "bond0",
          "faults": null,
        },
        "metadata": {
          "name": "cisco-access-2@GigabitEthernet1/0/27",
          "selfLink": "/api/v1/discoveredlinks/cisco-access-2%40GigabitEthernet1%2F0%2F27",
          "resourceVersion": "243",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "cisco-access-2",
          "localPort": "GigabitEthernet1/0/28",
          "remoteDevice": "cisco-dist-1",
          "remotePort": "GigabitEthernet1/0/26",
          "faults": null,
        },
        "metadata": {
          "name": "cisco-access-2@GigabitEthernet1/0/28",
          "selfLink": "/api/v1/discoveredlinks/cisco-access-2%40GigabitEthernet1%2F0%2F28",
          "resourceVersion": "207",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "cisco-access-2",
          "localPort": "GigabitEthernet1/0/29",
          "remoteDevice": "jnpr-dist-1",
          "remotePort": "ge-0/0/546",
          "faults": null,
        },
        "metadata": {
          "name": "cisco-access-2@GigabitEthernet1/0/29",
          "selfLink": "/api/v1/discoveredlinks/cisco-access-2%40GigabitEthernet1%2F0%2F29",
          "resourceVersion": "222",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "cisco-dist-1",
          "localPort": "GigabitEthernet1/0/26",
          "remoteDevice": "cisco-access-2",
          "remotePort": "GigabitEthernet1/0/28",
          "faults": null,
        },
        "metadata": {
          "name": "cisco-dist-1@GigabitEthernet1/0/26",
          "selfLink": "/api/v1/discoveredlinks/cisco-dist-1%40GigabitEthernet1%2F0%2F26",
          "resourceVersion": "231",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "cisco-dist-1",
          "localPort": "GigabitEthernet1/0/27",
          "remoteDevice": "cisco-access-1",
          "remotePort": "GigabitEthernet1/0/28",
          "faults": null,
        },
        "metadata": {
          "name": "cisco-dist-1@GigabitEthernet1/0/27",
          "selfLink": "/api/v1/discoveredlinks/cisco-dist-1%40GigabitEthernet1%2F0%2F27",
          "resourceVersion": "227",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "cisco-dist-1",
          "localPort": "GigabitEthernet1/0/28",
          "remoteDevice": "sonic2",
          "remotePort": "Ethernet0",
          "faults": null,
        },
        "metadata": {
          "name": "cisco-dist-1@GigabitEthernet1/0/28",
          "selfLink": "/api/v1/discoveredlinks/cisco-dist-1%40GigabitEthernet1%2F0%2F28",
          "resourceVersion": "217",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "cisco-dist-1",
          "localPort": "GigabitEthernet1/0/29",
          "remoteDevice": "sonic1",
          "remotePort": "Ethernet0",
          "faults": null,
        },
        "metadata": {
          "name": "cisco-dist-1@GigabitEthernet1/0/29",
          "selfLink": "/api/v1/discoveredlinks/cisco-dist-1%40GigabitEthernet1%2F0%2F29",
          "resourceVersion": "203",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "jnpr-dist-1",
          "localPort": "ge-0/0/546",
          "remoteDevice": "cisco-access-2",
          "remotePort": "GigabitEthernet1/0/29",
          "faults": null,
        },
        "metadata": {
          "name": "jnpr-dist-1@ge-0/0/546",
          "selfLink": "/api/v1/discoveredlinks/jnpr-dist-1%40ge-0%2F0%2F546",
          "resourceVersion": "234",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "jnpr-dist-1",
          "localPort": "ge-0/0/547",
          "remoteDevice": "cisco-access-1",
          "remotePort": "GigabitEthernet1/0/29",
          "faults": null,
        },
        "metadata": {
          "name": "jnpr-dist-1@ge-0/0/547",
          "selfLink": "/api/v1/discoveredlinks/jnpr-dist-1%40ge-0%2F0%2F547",
          "resourceVersion": "211",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "jnpr-dist-1",
          "localPort": "ge-0/0/548",
          "remoteDevice": "sonic2",
          "remotePort": "Ethernet0",
          "faults": null,
        },
        "metadata": {
          "name": "jnpr-dist-1@ge-0/0/548",
          "selfLink": "/api/v1/discoveredlinks/jnpr-dist-1%40ge-0%2F0%2F548",
          "resourceVersion": "221",
          "creationTimestamp": null,
        },
      },
      {
        "spec": null,
        "status": {
          "localDevice": "jnpr-dist-1",
          "localPort": "ge-0/0/549",
          "remoteDevice": "sonic1",
          "remotePort": "Ethernet0",
          "faults": null,
        },
        "metadata": {
          "name": "jnpr-dist-1@ge-0/0/549",
          "selfLink": "/api/v1/discoveredlinks/jnpr-dist-1%40ge-0%2F0%2F549",
          "resourceVersion": "209",
          "creationTimestamp": null,
        },
      },
    ],
  },
}
