
// GENERATED BY THE UNION OF WAVESURF ROBOTS

/*
Copyright (c) 2019 WaveSurf Systems Inc. All rights reserved.
*/

import {Component} from '@angular/core';

@Component({
  selector: 'kd-device-list-view',
  template: '<kd-device-list></kd-device-list>',
})
export class DeviceListComponent {}
